### ISSUE TITLE
Wrong interface implementation for psalm 4

### ISSUE THREAD

**Issue by GDXbsv** [alexeyshockov/guzzle-psalm-plugin#5]
Declaration of AlexS\Guzzle\PsalmPlugin::__invoke(Psalm\Plugin\RegistrationInterface $psalm, ?SimpleXMLElement $config = NULL) must be compatible with Psalm\Plugin\PluginEntryPointInterface::__invoke(Psalm\Plugin\RegistrationInterface $registration, ?SimpleXMLElement $config = NULL): void

**Comment by alexeyshockov** [comment]
Oh-oh, looks like it's not so simple as we thought in #4.

Will take a look when I have time, currently you can use stick with 0.2.0 and Psalm 3.x.

**Comment by rickogden** [comment]
This has been fixed in #6 .
